apiVersion: v1
kind: ConfigMap
metadata:
  name: deliverxy-config
  namespace: deliverxy
data:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/deliverxy"
  SPRING_DATASOURCE_USERNAME: "postgres"
  POSTGRES_DB: "deliverxy"
  POSTGRES_USER: "postgres"
  BACKEND_PORT: "8080"
  FRONTEND_PORT: "5173"
  POSTGRES_PORT: "5432"